package com.sever.physics.game.utils;

public enum WeaponTypes {
	BULLET, BOMB, BOMB_TRIPLE, BOMB_BIG, BOMB_IMPLODING, SHOCK_GUN, SUPER_SHOCK_GUN, MISSILE, MISSILE_LIGHT, MISSILE_LOCKING, BOMB_CAPSULES, BOSS1, BOSS2, BOSS3;
}
